config/routes.rb
Spendyserver::Application.routes.draw do
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :expenses, only: [:create, :edit, :update, :destroy]
  
  resources :relationships, only: [:create, :destroy]
  
  root :to => 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/tag',     to: 'tag#index',            via: 'get'
  
  
  match 'tagged' => 'expenses#tagged', :as => 'tagged'
  match 'enter'  => 'expenses#enter',  :as => 'enter'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_expense_form.html.erb
<%= form_for @expense, :builder => StandardFormBuilder do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.label :amount %>
    <%= f.text_field :amount, :type => 'tel', :onkeyup => "convertToFloat(this,event,2);", :value => @expense.amount ? @expense.amount : '0.00', :onfocus => 'setCursorAtEnd(this)' %>
    <%= f.label :tags %>
    <%=h f.text_field :tag_list %>
    <ul>
  </div>
  <%= f.submit "Submit", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="expenses">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="amount"><%= pretty_money(feed_item.user, feed_item.amount)  %></span>
  <div>
	<% feed_item.tags.any? %>
	  <% feed_item.tags.each do |tag| %>
	      <%= render partial: 'shared/tagged_tag', locals: {:tag => tag} %>  
	<% end %>
  </div>
  <span class="timestamp">
    <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.amount %>
    <%= link_to 'edit', edit_expense_path(feed_item) %>
  <% end %>
</li>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_tagged_tag.html.erb
<% if params[:tag] %>
  <% tagList = params[:tag].split(',') %>
  <% if tagList.include?(tag.name)%>
    <% tagList.delete(tag.name) %>
  <% else %>
    <% tagList.push(tag.name) %>
  <% end %>
  <%= link_to tag.name, tagged_url(params.merge(:tag => tagList.join(','))), :class => (tagList.include?(tag.name) ? 'btn btn-mini' : 'btn btn-mini btn-info')  %>
<% else %>
  <%= link_to tag.name, tagged_url(params.merge(:tag => tag.name)), :class =>  'btn btn-mini'  %>
<% end %> 

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.expenses.count, "expense") %>
</span>

app/views/shared/_user_list.html.erb
<% if params[:user] %>
  <% userList = params[:user].split(',') %>
  <% if userList.include?(user.id.to_s) %>
    <% userList.delete(user.id.to_s) %>
  <% else %>
    <% userList.push(user.id) %>
  <% end %>
  <%= link_to user.name, tagged_url(params.merge(:user => userList.join(','))), :class => (userList.include?(user.id) ? 'btn btn-mini btn-success' : 'btn btn-mini btn-danger')  %>
<% else %>
  <%= link_to user.name, tagged_url(params.merge(:user => user.id)), :class =>  'btn btn-mini btn-success'  %>
<% end %> 