config/routes.rb
Spendyserver::Application.routes.draw do
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :expenses, only: [:create, :edit, :update, :destroy]
  
  resources :relationships, only: [:create, :destroy]
  
  root :to => 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/tag',     to: 'tag#index',            via: 'get'
  
  
  match 'tagged' => 'expenses#tagged', :as => 'tagged'
  match 'enter'  => 'expenses#enter',  :as => 'enter'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation %>

  <%= f.label :week_start, "Week Starts" %>
  <%= f.hidden_field :week_start %>
      <div class="btn-group bottom-padd" data-toggle="buttons-radio" data-target="user_week_start">
        <button type="button" id="toggleButton6" class="btn <%= @user.week_start == 6 ? 'active' : '' %> btn-min-padd" data-toggle="button" value="6" onclick="javascript:document.getElementById('user_week_start').value=this.value" >
          Sun
        </button>
        <button type="button" id="toggleButton0" class="btn <%= @user.week_start == 0 ? 'active' : '' %> btn-min-padd" data-toggle="button" value="0" onclick="javascript:document.getElementById('user_week_start').value=this.value" >
          Mon
        </button>
        <button type="button" id="toggleButton1" class="btn <%= @user.week_start == 1 ? 'active' : '' %> btn-min-padd" data-toggle="button" value="1" onclick="javascript:document.getElementById('user_week_start').value=this.value" >
          Tue
        </button>
        <button type="button" id="toggleButton2" class="btn <%= @user.week_start == 2 ? 'active' : '' %> btn-min-padd" data-toggle="button" value="2" onclick="javascript:document.getElementById('user_week_start').value=this.value" >
          Wed
        </button>
        <button type="button" id="toggleButton3" class="btn <%= @user.week_start == 3 ? 'active' : '' %> btn-min-padd" data-toggle="button" value="3" onclick="javascript:document.getElementById('user_week_start').value=this.value" >
          Thur
        </button>
        <button type="button" id="toggleButton4" class="btn <%= @user.week_start == 4 ? 'active' : '' %> btn-min-padd" data-toggle="button" value="4" onclick="javascript:document.getElementById('user_week_start').value=this.value" >
          Fri
        </button>
        <button type="button" id="toggleButton5" class="btn <%= @user.week_start == 5 ? 'active' : '' %> btn-min-padd" data-toggle="button" value="5" onclick="javascript:document.getElementById('user_week_start').value=this.value" >
          Sat
        </button>
      </div>

    <%= f.label :currency_locale, "Currency Locale" %>
    <%= f.hidden_field :currency_locale %>
    <div class="btn-group bottom-padd" data-toggle="buttons-radio" data-target="user_currency_locale">
      <button type="button" id="localeButton0" class="btn <%= @user.currency_locale == '$' ? 'active' : '' %> " data-toggle="button" value="$" onclick="javascript:document.getElementById('user_currency_locale').value=this.value" >
        $
      </button>
      <button type="button" id="localeButton1" class="btn <%= @user.currency_locale == '£' ? 'active' : '' %> " data-toggle="button" value="£" onclick="javascript:document.getElementById('user_currency_locale').value=this.value" >
        £
      </button>
      <button type="button" id="localeButton2" class="btn <%= @user.currency_locale == '€' ? 'active' : '' %> " data-toggle="button" value="€" onclick="javascript:document.getElementById('user_currency_locale').value=this.value" >
        €
      </button>
    </div>    <br/>

  <%= f.submit yield(:submit_button_text), class: "btn btn-large btn-primary" %>

<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
	<div class="container">
	  <%= link_to image_tag("spendy_icon.png", size: "74x25", alt: "Spendy"), root_path, id: "logo" %>
	  <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
            <li><%= link_to current_user.currency_locale + current_user.currency_locale, tagged_url(:tag => '', :user => '') %></li>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
	</div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>  
    <%= stylesheet_link_tag "application", media: "all", 
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <html manifest="/app.manifest">
    <meta name="viewport"
      content="initial-scale=1.0">
    <meta name="viewport"
      content="width=320.1">
    <meta name="viewport"
     content="user-scalable=0">
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    
    <link href="/apple-touch-startup-image-320x460.png" 
          media="(device-width: 320px)"  
          rel="apple-touch-startup-image">
    
    <link href="/apple-touch-startup-image-640x920.png" 
          media="(device-width: 320px) 
             and (device-height: 480px) 
             and (-webkit-device-pixel-ratio: 2)" 
          rel="apple-touch-startup-image">
    
    <link href="/apple-touch-startup-image-640x1096.png" 
          media="(device-width: 320px) 
             and (device-height: 568px) 
             and (-webkit-device-pixel-ratio: 2)" 
          rel="apple-touch-startup-image">
    
    <link rel="apple-touch-icon-precomposed" href="/icon.png" />
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/icon@2x.png" />
    <%= render 'layouts/shim' %>
  </head>
  <body>
	<%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>  
    <%= stylesheet_link_tag "application", media: "all", 
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport"
      content="initial-scale=1.0">
    <meta name="viewport"
      content="width=320.1">
    <meta name="viewport"
     content="user-scalable=0">
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    
    <link href="/apple-touch-startup-image-320x460.png" 
          media="(device-width: 320px)"  
          rel="apple-touch-startup-image">
    
    <link href="/apple-touch-startup-image-640x920.png" 
          media="(device-width: 320px) 
             and (device-height: 480px) 
             and (-webkit-device-pixel-ratio: 2)" 
          rel="apple-touch-startup-image">
    
    <link href="/apple-touch-startup-image-640x1096.png" 
          media="(device-width: 320px) 
             and (device-height: 568px) 
             and (-webkit-device-pixel-ratio: 2)" 
          rel="apple-touch-startup-image">
    
    <link rel="apple-touch-icon-precomposed" href="/icon.png" />
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/icon@2x.png" />
    <%= render 'layouts/shim' %>
  </head>
  <style type="text/css">
    .bodee {
      background-image:url('/background.png');
      background-size: 100%;
      margin-top: 40px;
    }
	.fooStyle {
	  color: white;
	  text-shadow: black 0.1em 0.1em 0.2em;
	}
  </style>
  <body class="bodee">
    <div>  
	  <div class="center">
        <img src="/Spendy.png" alt="" style="width: 10.0em">
	  </div>  
	  <div class="row">
		  <div class="span6 offset3">
			<%= form_for(:session, url: sessions_path) do |f| %>
		
			  <%= f.label :email, class: "fooStyle" %>
			  <%= f.text_field :email %>
		
			  <%= f.label :password, class: "fooStyle" %>
			  <%= f.password_field :password %>
		
			   <div class="center"><%= f.submit "Sign in", class: "btn btn-large btn-primary" %></div>
			<% end %>
		    
			 <div class="center">
			   <p>New user? <%= link_to "Sign up now!", signup_path %></p>
			   <p>Learn More <%= link_to "About", about_path %> Spendy</p>
			</div>
		  </div>
	  </div>
    </div>
  </body>
</html>